- name: Instalacja docker i docker-compose
  pip:
    name: 
    - docker
    - docker-compose

- name: Klonowanie repozytorium
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- name: Uruchamianie docker-compose
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
    debug: yes
